### ISSUE TITLE
forum.rejectedsoftware.com - error when posting new topic

### ISSUE THREAD

**Issue by logicfish** [rejectedsoftware/vibenews#38] opened 2017-07-12 12:49 UTC
"Unknown article id!"

**Comment by s-ludwig** [comment] 2017-07-12 12:57
My guess would be that this is a symptom of the same cause as in #8. However, I can't see a recent message that was falsely flagged as spam. When/in which forum did you post when it failed?

**Comment by s-ludwig** [comment] 2020-06-09 08:07
Closing as duplicate of #8

**Closed by s-ludwig** 2020-06-09 08:07 UTC
